### ISSUE TITLE
BACKEND: Allow users to register an account

### ISSUE THREAD

**Issue by grant-baer** [grant-baer/Picture-Perfect-Project#1]
Acceptance Criteria:
- Aesthetically pleasing registration form that fits the theme of the project
- User is able to submit registration info into the form
- Frontend enforces password rules and hashes passwords.
- Frontend sends data to backend.
- Backend handles registration requests. For now this can be a dummy endpoint (once/if the DB is up, the handler must also check the username is unique and write the user to the user table).

Notes:
- Registration info:
        - Name
        - Username
        - Password

**Comment by caseyavila** [comment]
Estimated time: 2 hours

**Comment by caseyavila** [comment]
Dependent on #12
