### ISSUE TITLE
connect app to Dalle

### ISSUE THREAD

**Issue by grant-baer** [grant-baer/Picture-Perfect-Project#2]
SPRINT 1 - WEEK 2 
- - connect Dalle API to backend
- create UI textbox for users to enter prompt
- submit button to send to API and receive a URL to give back to user

**Comment by grant-baer** [comment]
```
response = openai.Image.create(
  prompt="a white siamese cat",
  n=1,
  size="1024x1024"
)
image_url = response['data'][0]['url']
```

**Comment by caseyavila** [comment]
Estimated time: 4 hours

**Comment by caseyavila** [comment]
Completed time: 4 hours
